default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  username: <%= ENV.fetch('DB_USER', (`whoami`).strip) %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: nutrebem_development

test:
  <<: *default
  database: nutrebem_test<%= ENV['TEST_ENV_NUMBER'] %>


production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
  sslmode: require